name       : haskell-byteable
version    : 0.1.1
release    : 2
source     :
    - http://hackage.haskell.org/package/byteable-0.1.1/byteable-0.1.1.tar.gz : 243b34a1b5b64b39e39fe58f75c18f6cad5b668b10cabcd86816cbde27783fe2
license    : BSD-3-Clause
component  : programming.haskell
summary    : Abstract class to manipulate sequence of bytes
description: |
    The use case of this class is abstracting manipulation of types that are just wrapping a bytestring with stronger and more meaniful name.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
